[app]
debug = false # Enable debug logging

[mqtt]
url = "tcp://localhost:1883"

[emodul]
apiUrl = "https://emodul.eu/api/v1"
frontendUrl = "https://emodul.eu"
username = ""
password = ""
moduleid = ""

[rest]
host = "localhost"
port = 8833
jwtSecret = ""

[snapcast]
apiUrl = "https://snapcast.oja.me"

[homeassistant]
apiUrl = "https://hass.oja.me/api"
token = ""
